### ISSUE TITLE
Compile it?

### ISSUE THREAD

**Issue by Resoluciones** [simonmeusel/minecraft-pre-gen#1]
Hi!  Would it be possible sombody can compilie it against last paper/spigot/bukkit 1.13?

Thanks!!!!

**Comment by simonmeusel** [comment]
This works with every mc version, if it supports the tp command, even vanilla.

You just need to install nodejs https://nodejs.org/en/ and run

```
npm i minecraft-pre-gen -g
```

and

```
mcpg g 300 60
```

in the terminal
